### ISSUE TITLE
lychee.toml

### ISSUE THREAD

**Issue by mre** [hello-rust/lychee#14]
Providing a lot of command-line flags can get tedious and repetitive quite quickly.
Consider the following example:

```
lychee --verbose --progress --max-redirects 2 --user-agent "lychee" --insecure --exclude "github.com --exclude-all-private --timeout 10
```

As an alternative I'd love to have a `lychee.toml` file, which can be used instead of manually specifying the flags:

```toml
verbose = true
progress = true
max-redirects = 2
user-agent = lychee
insecure = true
exclude = [
  "github.com"
]
exclude-all-private = true
timeout = 10
```

Then whenever `lychee` is called, it would look for the `lychee.toml` file and read the parameters. Parameters could still be overwritten from the command-line. (E.g. `lychee --timeout=11` would overwrite the timeout from the config.)

If you're interested in working on this, add a comment and I'll assign it to you.
